name: assignment-autotest-test
on: [push]
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment3
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh

            run: ./unit-test.sh
